import { Announcement } from '@core/models/announcement.model';
import { Employee } from '@core/models/employee.model';

/**
 * Seed data served by the mock backend interceptor. `bioHtml` intentionally
 * contains markup (and one hostile payload) so the Security module has something
 * real to sanitise.
 */
export const EMPLOYEE_SEED: readonly Employee[] = [
  {
    id: 1,
    firstName: 'Aarav',
    lastName: 'Mehta',
    email: 'aarav.mehta@acme.io',
    title: 'Principal Engineer',
    department: 'Engineering',
    role: 'ADMIN',
    status: 'ACTIVE',
    salary: 189000,
    joinedOn: '2017-03-06',
    location: 'Bengaluru',
    skills: ['Angular', 'RxJS', 'Architecture', 'Nx'],
    bioHtml:
      '<p>Owns the <strong>platform architecture</strong> guild. ' +
      '<img src="x" onerror="alert(\'XSS from bio\')"> Writes more RFCs than code.</p>',
    avatarColor: '#6366f1',
  },
  {
    id: 2,
    firstName: 'Riya',
    lastName: 'Sharma',
    email: 'riya.sharma@acme.io',
    title: 'Engineering Manager',
    department: 'Engineering',
    role: 'MANAGER',
    status: 'ACTIVE',
    salary: 172000,
    joinedOn: '2019-08-19',
    location: 'Pune',
    skills: ['Delivery', 'Coaching', 'TypeScript'],
    bioHtml: '<p>Runs the payments squad. Ex-consultant, recovering.</p>',
    avatarColor: '#0ea5e9',
  },
  {
    id: 3,
    firstName: 'Daniel',
    lastName: 'Okafor',
    email: 'daniel.okafor@acme.io',
    title: 'Senior Frontend Engineer',
    department: 'Engineering',
    role: 'EMPLOYEE',
    status: 'ACTIVE',
    salary: 141000,
    joinedOn: '2021-01-11',
    location: 'Lagos',
    skills: ['Angular', 'Signals', 'Testing'],
    bioHtml: '<p>Signals evangelist. <em>Zoneless or bust.</em></p>',
    avatarColor: '#22c55e',
  },
  {
    id: 4,
    firstName: 'Mei',
    lastName: 'Tanaka',
    email: 'mei.tanaka@acme.io',
    title: 'Product Designer',
    department: 'Design',
    role: 'EMPLOYEE',
    status: 'ON_LEAVE',
    salary: 118000,
    joinedOn: '2020-05-04',
    location: 'Osaka',
    skills: ['Design systems', 'Figma', 'Accessibility'],
    bioHtml: '<p>Keeps the component library honest.</p>',
    avatarColor: '#f97316',
  },
  {
    id: 5,
    firstName: 'Sofia',
    lastName: 'Ramirez',
    email: 'sofia.ramirez@acme.io',
    title: 'Finance Analyst',
    department: 'Finance',
    role: 'EMPLOYEE',
    status: 'ACTIVE',
    salary: 96000,
    joinedOn: '2022-02-14',
    location: 'Madrid',
    skills: ['Forecasting', 'SQL', 'Excel'],
    bioHtml: '<p>Owns headcount planning.</p>',
    avatarColor: '#e11d48',
  },
  {
    id: 6,
    firstName: 'Noah',
    lastName: 'Fischer',
    email: 'noah.fischer@acme.io',
    title: 'People Partner',
    department: 'People Ops',
    role: 'MANAGER',
    status: 'ACTIVE',
    salary: 104000,
    joinedOn: '2018-11-26',
    location: 'Berlin',
    skills: ['Hiring', 'Policy', 'Mediation'],
    bioHtml: '<p>Runs onboarding and the internal mobility programme.</p>',
    avatarColor: '#8b5cf6',
  },
  {
    id: 7,
    firstName: 'Ishita',
    lastName: 'Rao',
    email: 'ishita.rao@acme.io',
    title: 'QA Engineer',
    department: 'Engineering',
    role: 'EMPLOYEE',
    status: 'PROBATION',
    salary: 88000,
    joinedOn: '2025-06-02',
    location: 'Hyderabad',
    skills: ['Playwright', 'Vitest', 'CI'],
    bioHtml: '<p>Automates everything twice.</p>',
    avatarColor: '#14b8a6',
  },
  {
    id: 8,
    firstName: 'Liam',
    lastName: 'O’Connor',
    email: 'liam.oconnor@acme.io',
    title: 'Account Executive',
    department: 'Sales',
    role: 'EMPLOYEE',
    status: 'ACTIVE',
    salary: 112000,
    joinedOn: '2023-09-18',
    location: 'Dublin',
    skills: ['Enterprise sales', 'Negotiation'],
    bioHtml: '<p>Closed the largest deal of FY25.</p>',
    avatarColor: '#eab308',
  },
  {
    id: 9,
    firstName: 'Amara',
    lastName: 'Diallo',
    email: 'amara.diallo@acme.io',
    title: 'Support Lead',
    department: 'Support',
    role: 'MANAGER',
    status: 'ACTIVE',
    salary: 94000,
    joinedOn: '2019-04-01',
    location: 'Dakar',
    skills: ['Escalations', 'Zendesk', 'Process'],
    bioHtml: '<p>Cut first-response time in half.</p>',
    avatarColor: '#06b6d4',
  },
  {
    id: 10,
    firstName: 'Tomas',
    lastName: 'Nowak',
    email: 'tomas.nowak@acme.io',
    title: 'Data Engineer',
    department: 'Engineering',
    role: 'EMPLOYEE',
    status: 'EXITED',
    salary: 133000,
    joinedOn: '2016-07-25',
    location: 'Kraków',
    skills: ['Airflow', 'dbt', 'Python'],
    bioHtml: '<p>Built the first warehouse. Alumni network member.</p>',
    avatarColor: '#a855f7',
  },
];

/**
 * Seeded company announcements. The first entry deliberately carries a hostile
 * payload: announcements are authored by humans through a rich-text field, so
 * the render path must sanitise, and this proves it does.
 */
export const ANNOUNCEMENT_SEED: readonly Announcement[] = [
  {
    id: 1,
    title: 'Open enrolment closes 30 September',
    bodyHtml:
      '<p>Benefits open enrolment closes at <strong>17:00 on 30 September</strong>. ' +
      'Review your elections in the People Ops portal.</p>' +
      '<p><em>Questions?</em> Ask in #people-ops.</p>',
    author: 'Noah Fischer',
    postedAt: '2026-09-01T09:00:00.000Z',
    pinned: true,
  },
  {
    id: 2,
    title: 'Engineering all-hands moved to Thursday',
    bodyHtml:
      '<p>This month’s all-hands moves to <strong>Thursday 14:00</strong>. ' +
      'The agenda covers the platform roadmap and Q4 hiring.</p>' +
      '<img src="x" onerror="alert(\'XSS in announcement\')">',
    author: 'Riya Sharma',
    postedAt: '2026-08-28T11:30:00.000Z',
    pinned: false,
  },
  {
    id: 3,
    title: 'Welcome to our new joiners',
    bodyHtml: '<p>Please welcome <strong>Ishita Rao</strong> to the QA team.</p>',
    author: 'Noah Fischer',
    postedAt: '2026-08-20T08:15:00.000Z',
    pinned: false,
  },
];
